name: Expo Publish(Develop)
on:
  push:
    branches:
      - develop
      
env: 
  AMPLITUDE_KEY: ${{ secrets.AMPLITUDE_KEY_DEV }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
jobs:
  publish:
    name: Install and publish(Develop)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: yarn build:develop
